pipeline {
    agent none
        
    stages {
        stage('Build') {
            agent any
            steps {
                sh '/Users/hakanyildirim/workdir/apache-maven-3.8.6/bin/mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            agent any
            steps {
                sh '/Users/hakanyildirim/workdir/apache-maven-3.8.6/bin/mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            agent any
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
